#Task 1 :Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library).

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
inputs = np.array([[73, 67, 43],
                    [91, 88, 64],
                    [87, 134, 58],
                    [102, 43, 37],
                    [69, 96, 70],
                    [73, 67, 43],
                    [91, 88, 64],
                    [87, 134, 58],
                    [102, 43, 37],
                    [69, 96, 70],
                    [73, 67, 43], 
                    [91, 88, 64], 
                    [87, 134, 58], 
                    [102, 43, 37], 
                    [69, 96, 70]], dtype='float32')
print(inputs.shape)

(15, 3)


In [3]:
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(inputs,targets,test_size=0.3, random_state=8)

In [11]:
reg = LinearRegression().fit(x_train,y_train)
print(reg)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)


In [12]:
print(reg.intercept_)
print(reg.coef_)

[-5.052086  -1.9788971]
[[-0.36587772  0.83573174  0.74966705]
 [-0.28667942  0.79484916  0.92136675]]


In [13]:
y_pred = reg.predict(x_test)
print(y_pred,"\n")
print(y_test)

[[ 83.176125 100.84747 ]
 [ 83.176125 100.84747 ]
 [118.5853   133.02905 ]
 [118.5853   133.02905 ]
 [ 21.302534  37.048885]] 

[[ 81. 101.]
 [ 81. 101.]
 [119. 133.]
 [119. 133.]
 [ 22.  37.]]


In [14]:
from sklearn import metrics
print('\n Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))


 Mean Squared Error: 1.035206
