#Task2: Try Linear regression on same prediction data using Tensorflow

In [9]:
import numpy as np
import tensorflow as tf

In [2]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70],[73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70]], dtype='float64')

targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], 
                    [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float64')

In [3]:
inputs = tf.Variable(inputs)
targets = tf.Variable(targets)
print("targets :\n",targets)

targets :
 <tf.Variable 'Variable:0' shape=(15, 2) dtype=float64, numpy=
array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]])>


In [4]:
v = np.random.rand(3,2)
r = np.random.randn(2)
v = tf.Variable(v)
r = tf.Variable(r)

print(v)
print("\n",r)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float64, numpy=
array([[0.46262758, 0.78796204],
       [0.85992879, 0.52667661],
       [0.33017074, 0.76194342]])>

 <tf.Variable 'Variable:0' shape=(2,) dtype=float64, numpy=array([0.42572415, 1.31166704])>


In [5]:
def model(s):
    return s @ v + r

In [6]:
prediction = model(inputs)
print(prediction)

tf.Tensor(
[[106.01010819 126.88379616]
 [139.32949474 168.12813355]
 [175.05468448 184.63174896]
 [ 96.80699247 132.52279629]
 [138.01214281 159.57804195]
 [106.01010819 126.88379616]
 [139.32949474 168.12813355]
 [175.05468448 184.63174896]
 [ 96.80699247 132.52279629]
 [138.01214281 159.57804195]
 [106.01010819 126.88379616]
 [139.32949474 168.12813355]
 [175.05468448 184.63174896]
 [ 96.80699247 132.52279629]
 [138.01214281 159.57804195]], shape=(15, 2), dtype=float64)


In [7]:
def mse(t1,t2):
    return tf.reduce_mean(tf.square(t1 - t2))
print(mse(prediction,targets))

tf.Tensor(3704.637697597697, shape=(), dtype=float64)


In [8]:
epochs = 40
for epoch_count in range(epochs):
    
    with tf.GradientTape(persistent=True) as t:
        current_loss = mse(targets, model(inputs))

    v1 = t.gradient(current_loss,v)
    r1 = t.gradient(current_loss,r)

    v.assign_sub(1e-4 * v1)
    r.assign_sub(1e-4 * r1)
        
    print(f" \n Epoch count: {epoch_count} \n Loss value: {current_loss.numpy()}")


 
 Epoch count: 0 
 Loss value: 3704.637697597697
 
 Epoch count: 1 
 Loss value: 2441.4522198765744
 
 Epoch count: 2 
 Loss value: 1636.6267068196455
 
 Epoch count: 3 
 Loss value: 1120.3271531808869
 
 Epoch count: 4 
 Loss value: 786.0882152809912
 
 Epoch count: 5 
 Loss value: 567.1144509630502
 
 Epoch count: 6 
 Loss value: 421.4511928402279
 
 Epoch count: 7 
 Loss value: 322.70463054012026
 
 Epoch count: 8 
 Loss value: 254.23380853427037
 
 Epoch count: 9 
 Loss value: 205.51494987516602
 
 Epoch count: 10 
 Loss value: 169.86504980062827
 
 Epoch count: 11 
 Loss value: 143.01606131007526
 
 Epoch count: 12 
 Loss value: 122.22141664631924
 
 Epoch count: 13 
 Loss value: 105.69575933169452
 
 Epoch count: 14 
 Loss value: 92.26329224842162
 
 Epoch count: 15 
 Loss value: 81.13677620655463
 
 Epoch count: 16 
 Loss value: 71.77838674913436
 
 Epoch count: 17 
 Loss value: 63.81188977081873
 
 Epoch count: 18 
 Loss value: 56.967017284287444
 
 Epoch count: 19 
 Loss valu